name: Deploy

on: push

jobs:
  webapp_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            apps
            packages
            deno.json
            deno.lock
            importMap.json
            importMap.local.json

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: project_name
          entrypoint: apps/webapp/server.tsx
